extends GdUnitTestSuite

## Tests for the deep-space encounter field: that a cell's contents come out the same
## every time, that the rings carry their cells around as they turn, that harvested slots
## stay harvested, and that the field stays out of the space the planet spawners own.

const PLANET_SCENE := preload("res://entities/Planet/Planet.tscn")
## A ring out in the void between Sonder and Crom, well clear of the sun's exclusion.
const DEEP := 18


## A def that builds plain Node2Ds, so cell logic can be tested without the resource pool.
class MarkerDef extends EncounterDef:
	var nodes_per_encounter := 3
	## Cartesian, like a real encounter's — so a cluster keeps its shape rather than
	## being smeared round the ring. Set to 0 to plant everything exactly on the origin.
	var spread := 100.0

	func plan(rng: RandomNumberGenerator, origin: Vector2) -> Array[Dictionary]:
		var entries: Array[Dictionary] = []
		for i in nodes_per_encounter:
			entries.append({"pos": origin + Vector2(rng.randf(), rng.randf()) * spread})
		return entries

	func build(field: Node2D, entry: Dictionary) -> Node:
		var node := Node2D.new()
		node.global_position = entry["pos"]
		field.add_child(node)
		return node


func _table(per_cell: int = 1, spread: float = 100.0) -> EncounterTable:
	var def := MarkerDef.new()
	def.id = &"marker"
	def.spread = spread
	var table := EncounterTable.new()
	table.entries = [def]
	table.min_per_cell = per_cell
	table.max_per_cell = per_cell
	return table


## A field in the tree but not streaming — cells are generated by hand.
func _field(table: EncounterTable = null, turned: float = 0.0) -> EncounterField:
	var field := auto_free(EncounterField.new()) as EncounterField
	field.enabled = false
	field.table = table if table else _table()
	add_child(field)
	field.restore({"elapsed": turned})
	return field


## Every node the contacts hold, in generation order.
func _nodes(contacts: Array) -> Array[Node]:
	var out: Array[Node] = []
	for contact in contacts:
		out.append_array((contact as EncounterContact).nodes)
	return out


func _positions(nodes: Array) -> Array[Vector2]:
	var out: Array[Vector2] = []
	for node in nodes:
		out.append((node as Node2D).global_position)
	return out


## Where a world point sits inside its ring, ignoring how far the ring has turned.
func _ring_local(field: EncounterField, band: int, world_position: Vector2) -> Vector2:
	var offset := world_position - field.centre()
	return Vector2(offset.length(), fposmod(offset.angle() - field.band_rotation(band), TAU))



# --- Cell geometry -----------------------------------------------------------

func test_a_world_position_lands_in_the_ring_and_sector_that_hold_it() -> void:
	var field := _field()
	var mid := field.band_mid(DEEP)
	assert_object(field.cell_of(Vector2.RIGHT * mid)).is_equal(Vector2i(DEEP, 0))
	# Two and a half sectors round is still inside sector 2
	var step := field.angle_step(DEEP)
	assert_object(field.cell_of(Vector2.RIGHT.rotated(step * 2.5) * mid)).is_equal(Vector2i(DEEP, 2))
	# One ring further out
	assert_int(field.cell_of(Vector2.RIGHT * (mid + EncounterField.BAND_WIDTH)).x).is_equal(DEEP + 1)


func test_sectors_are_about_as_wide_as_a_ring_is_thick() -> void:
	var field := _field()
	for band in [4, DEEP, 31]:
		var arc: float = field.angle_step(band) * field.band_mid(band)
		assert_float(arc).is_between(EncounterField.BAND_WIDTH * 0.75, EncounterField.BAND_WIDTH * 1.25)


func test_the_middle_of_a_cell_maps_back_to_it() -> void:
	var field := _field(null, 4000.0)
	for cell in [Vector2i(DEEP, 0), Vector2i(DEEP, 57), Vector2i(4, 2), Vector2i(31, 100)]:
		assert_object(field.cell_of(field.cell_centre(cell))).is_equal(cell)


func test_neighbouring_cells_get_unrelated_seeds() -> void:
	var seeds := {}
	for band in range(DEEP - 3, DEEP + 4):
		for sector in range(-3, 4):
			seeds[EncounterField.cell_seed(Vector2i(band, sector))] = true
	assert_int(seeds.size()).is_equal(49)


# --- The rings turn ----------------------------------------------------------

func test_a_cell_is_carried_round_as_its_ring_turns() -> void:
	var cell := Vector2i(DEEP, 10)
	var still := _field()
	var turned := _field(null, 20000.0)

	var moved := still.cell_centre(cell).distance_to(turned.cell_centre(cell))
	assert_float(moved).is_greater(EncounterField.BAND_WIDTH)
	# It moved, but it is still the same cell, and still in the same ring
	assert_object(turned.cell_of(turned.cell_centre(cell))).is_equal(cell)
	assert_float(turned.cell_centre(cell).length()).is_equal_approx(still.cell_centre(cell).length(), 1.0)


func test_inner_rings_turn_faster_than_outer_ones() -> void:
	var field := _field()
	var previous := INF
	for band in [4, 8, DEEP, 31]:
		var rate := field.band_rate(band)
		assert_float(rate).is_less(previous)
		previous = rate


func test_rings_drift_apart_from_each_other() -> void:
	# Nothing in the field is locked to anything else in it, which is what makes the
	# space between two planets different on the next crossing.
	var field := _field(null, 30000.0)
	var inner := field.band_rotation(6)
	var outer := field.band_rotation(31)
	assert_float(absf(inner - outer)).is_greater(0.1)


func test_the_drift_stays_gentle_everywhere() -> void:
	var field := _field()
	for band in range(3, 40):
		var speed := field.band_rate(band) * field.band_mid(band)
		assert_float(speed).is_between(1.0, EncounterField.MAX_DRIFT_SPEED)


# --- Determinism -------------------------------------------------------------

func test_a_cell_generates_the_same_contents_every_time() -> void:
	var cell := Vector2i(DEEP, 4)
	var first := _nodes(_field()._generate(cell))
	var second := _nodes(_field()._generate(cell))
	assert_int(first.size()).is_greater(0)
	assert_array(_positions(second)).is_equal(_positions(first))


func test_a_turned_ring_holds_the_same_cell_in_a_new_place() -> void:
	var cell := Vector2i(DEEP, 4)
	# No spread, so every marker sits on its encounter's origin and the ring's turn is
	# the only thing that can move it.
	var still := _field(_table(1, 0.0))
	var turned := _field(_table(1, 0.0), 20000.0)

	var before := _nodes(still._generate(cell))
	var after := _nodes(turned._generate(cell))
	assert_int(before.size()).is_greater(0)
	assert_int(after.size()).is_equal(before.size())

	for i in before.size():
		# The same distance out, so the ring turned rather than drifted
		assert_float(_ring_local(turned, DEEP, after[i].global_position).x) \
			.is_equal_approx(_ring_local(still, DEEP, before[i].global_position).x, 2.0)
		# ...and still owned by the cell that made it, in both
		assert_object(still.cell_of(before[i].global_position)).is_equal(cell)
		assert_object(turned.cell_of(after[i].global_position)).is_equal(cell)

	# But somewhere else entirely in the world
	assert_array(_positions(after)).is_not_equal(_positions(before))
	assert_float(after[0].global_position.distance_to(before[0].global_position)) \
		.is_greater(EncounterField.BAND_WIDTH)


func test_different_cells_generate_different_contents() -> void:
	var field := _field()
	var a := _positions(_nodes(field._generate(Vector2i(DEEP, 4))))
	var b := _positions(_nodes(field._generate(Vector2i(DEEP, 5))))
	assert_array(b).is_not_equal(a)


func test_generation_does_not_disturb_the_shared_rng() -> void:
	# Field generation must draw from its own seeded generator: pulling from RNG.rng
	# would shift every gameplay roll depending on where the player happened to fly.
	RNG.rng.seed = 99
	var expected := RNG.rng.randi()
	RNG.rng.seed = 99
	_field(_table(2))._generate(Vector2i(DEEP, 9))
	assert_int(RNG.rng.randi()).is_equal(expected)


# --- Consumption -------------------------------------------------------------

func test_harvested_slots_are_skipped_when_the_cell_comes_back() -> void:
	var cell := Vector2i(DEEP, 4)
	var field := _field()
	var before := _nodes(field._generate(cell))
	assert_int(before.size()).is_greater(1)

	var taken := "%d:%d:0" % [cell.x, cell.y]
	field.load_consumed(PackedStringArray([taken]))
	var after := _positions(_nodes(field._generate(cell)))

	assert_int(after.size()).is_equal(before.size() - 1)
	# The survivors keep their places: a slot index means the same thing either way
	assert_array(after).is_equal(_positions(before).slice(1))


func test_a_slot_stays_harvested_however_far_the_ring_has_turned() -> void:
	var cell := Vector2i(DEEP, 4)
	var full := _nodes(_field()._generate(cell)).size()
	var field := _field(null, 50000.0)
	field.load_consumed(PackedStringArray(["%d:%d:0" % [cell.x, cell.y]]))
	assert_int(_nodes(field._generate(cell)).size()).is_equal(full - 1)


func test_the_field_saves_its_slots_and_how_far_it_has_turned() -> void:
	var field := _field(null, 1234.5)
	field.load_consumed(PackedStringArray(["18:2:0", "18:2:3"]))

	var snapshot := field.snapshot()
	assert_float(snapshot["elapsed"]).is_equal_approx(1234.5, 0.001)

	var restored := _field()
	restored.restore(snapshot)
	var keys := restored.consumed_keys()
	keys.sort()
	assert_array(Array(keys)).is_equal(["18:2:0", "18:2:3"])
	assert_float(restored.elapsed()).is_equal_approx(1234.5, 0.001)


func test_a_new_game_forgets_what_earlier_runs_took_and_unwinds_the_rings() -> void:
	var field := _field(null, 900.0)
	field.load_consumed(PackedStringArray(["18:4:0"]))
	field.reset()
	assert_array(Array(field.consumed_keys())).is_empty()
	assert_float(field.elapsed()).is_equal(0.0)


# --- Exclusions --------------------------------------------------------------

func test_rings_near_the_sun_stay_empty() -> void:
	var field := _field()
	var checked := 0
	for band in range(0, 10):
		if field.band_mid(band) >= EncounterField.SUN_EXCLUSION:
			continue
		assert_array(_nodes(field._generate(Vector2i(band, 0)))).is_empty()
		checked += 1
	assert_int(checked).is_greater(0)


func test_nothing_is_placed_out_in_the_void() -> void:
	# Past the last orbit is VoidZone's, where nothing reflects and nothing answers.
	# Salvage floating there would spoil it and bait the player over a line they can't
	# safely cross.
	var field := _field()
	var first_void_band := field.band_of(VoidZone.EDGE_RADIUS) + 1
	for band in range(first_void_band, first_void_band + 6):
		assert_float(field.band_mid(band)).is_greater(VoidZone.EDGE_RADIUS)
		assert_array(_nodes(field._generate(Vector2i(band, 0)))).is_empty()

	# ...and the last ring inside it still works
	var last_inside := field.band_of(VoidZone.EDGE_RADIUS) - 1
	assert_float(field.band_mid(last_inside)).is_less(VoidZone.EDGE_RADIUS)
	assert_int(_nodes(field._generate(Vector2i(last_inside, 0))).size()).is_greater(0)


func test_encounters_keep_clear_of_planet_gravity_fields() -> void:
	var cell := Vector2i(DEEP, 4)
	var field := _field()
	assert_int(_nodes(field._generate(cell)).size()).is_greater(0)

	var planet := auto_free(PLANET_SCENE.instantiate()) as Planet
	planet.radius = EncounterField.BAND_WIDTH
	planet.gravity_radius_multiplier = 3.0
	add_child(planet)
	planet.global_position = field.cell_centre(cell)

	assert_array(_nodes(field._generate(cell))).is_empty()


# --- Table -------------------------------------------------------------------

func test_only_defs_banded_for_this_distance_are_in_play() -> void:
	var inner := MarkerDef.new()
	inner.id = &"inner"
	inner.max_radius = 100000.0
	var outer := MarkerDef.new()
	outer.id = &"outer"
	outer.min_radius = 100000.0

	var table := EncounterTable.new()
	table.entries = [inner, outer]

	assert_int(table.eligible(50000.0).size()).is_equal(1)
	assert_str(str(table.eligible(50000.0)[0].id)).is_equal("inner")
	assert_str(str(table.eligible(250000.0)[0].id)).is_equal("outer")
	# The boundary belongs to both: bands are inclusive at their edges
	assert_int(table.eligible(100000.0).size()).is_equal(2)


func test_picking_always_costs_one_draw_even_with_nothing_eligible() -> void:
	var table := EncounterTable.new()
	table.entries = []
	var rng := RandomNumberGenerator.new()
	rng.seed = 5
	assert_object(table.pick(rng, 50000.0)).is_null()

	var control := RandomNumberGenerator.new()
	control.seed = 5
	control.randf()
	assert_float(rng.randf()).is_equal(control.randf())


func test_weight_decides_the_share_of_picks() -> void:
	var common := MarkerDef.new()
	common.id = &"common"
	common.weight = 9.0
	var rare := MarkerDef.new()
	rare.id = &"rare"
	rare.weight = 1.0

	var table := EncounterTable.new()
	table.entries = [common, rare]

	var rng := RandomNumberGenerator.new()
	rng.seed = 1
	var rares := 0
	for i in 1000:
		if table.pick(rng, 50000.0).id == &"rare":
			rares += 1
	assert_int(rares).is_between(60, 140)


func test_a_zero_weight_def_never_turns_up() -> void:
	var off := MarkerDef.new()
	off.id = &"off"
	off.weight = 0.0
	var table := EncounterTable.new()
	table.entries = [off]
	assert_array(table.eligible(50000.0)).is_empty()


# --- The real table ----------------------------------------------------------

func test_the_shipped_table_builds_a_cluster_of_pooled_nodes() -> void:
	var table: EncounterTable = load("res://entities/encounters/tables/deep_space.tres")
	assert_object(table).is_not_null()
	assert_int(table.entries.size()).is_greater(0)

	var def := table.entries[0] as DebrisClusterDef
	assert_object(def).is_not_null()

	var rng := RandomNumberGenerator.new()
	rng.seed = 3
	var entries := def.plan(rng, Vector2(120000.0, 0.0))
	assert_int(entries.size()).is_between(def.min_nodes, def.max_nodes)
	for entry in entries:
		assert_float(entry["pos"].distance_to(Vector2(120000.0, 0.0))).is_less_equal(def.spread)
		assert_bool(ResourceNodePool.RESOURCE_SCENES.has(entry["variant"])).is_true()


# --- How empty the void is ---------------------------------------------------

func test_most_cells_hold_nothing() -> void:
	# The dial that decides whether finding something is an event or scenery.
	var table := _table()
	table.chance_per_cell = 0.3
	table.min_per_cell = 1
	table.max_per_cell = 1
	var field := _field(table)

	var populated := 0
	for sector in range(0, 200):
		if not field._generate(Vector2i(DEEP, sector)).is_empty():
			populated += 1
	assert_int(populated).is_between(40, 80)  # 0.3 of 200, with room for the roll


func test_the_shipped_void_is_mostly_void() -> void:
	var table: EncounterTable = load("res://entities/encounters/tables/deep_space.tres")
	assert_float(table.chance_per_cell).is_less(0.5)


func test_an_empty_cell_never_shifts_what_a_full_one_would_hold() -> void:
	# roll_count always draws exactly one number, so a cell coming up empty can't slide
	# the rest of the sequence and change its neighbours.
	var table := EncounterTable.new()
	table.chance_per_cell = 0.0
	var rng := RandomNumberGenerator.new()
	rng.seed = 4
	assert_int(table.roll_count(rng)).is_equal(0)

	var control := RandomNumberGenerator.new()
	control.seed = 4
	control.randf()
	assert_float(rng.randf()).is_equal(control.randf())


func test_a_certain_table_always_fires() -> void:
	var table := EncounterTable.new()
	table.chance_per_cell = 1.0
	table.min_per_cell = 2
	table.max_per_cell = 2
	var rng := RandomNumberGenerator.new()
	rng.seed = 1
	for i in 20:
		assert_int(table.roll_count(rng)).is_equal(2)


# --- Contacts ----------------------------------------------------------------

func test_a_cluster_of_many_pieces_is_one_contact() -> void:
	var field := _field()
	var cell := Vector2i(DEEP, 2)
	var contacts := field._generate(cell)
	field._cells[cell] = contacts

	assert_int(contacts.size()).is_equal(1)
	assert_int(contacts[0].remaining()).is_greater(1)
	assert_int(field.node_count()).is_equal(contacts[0].remaining())


func test_a_contact_sits_in_the_middle_of_what_is_left() -> void:
	var field := _field()
	var contact := EncounterContact.new("DEBRIS")
	for offset in [Vector2(-100, 0), Vector2(100, 0), Vector2(0, 300)]:
		var node := Node2D.new()
		field.add_child(node)
		node.global_position = offset
		contact.add(node)

	assert_vector(contact.position()).is_equal_approx(Vector2(0, 100), Vector2.ONE)

	# Salvage one and it re-centres on the rest
	var taken := contact.nodes[2]
	contact.drop(taken)
	taken.queue_free()
	assert_int(contact.remaining()).is_equal(2)
	assert_vector(contact.position()).is_equal_approx(Vector2.ZERO, Vector2.ONE)


func test_an_emptied_contact_stops_reporting() -> void:
	var field := _field()
	var contact := EncounterContact.new("DEBRIS")
	assert_bool(contact.is_alive()).is_false()

	var node := Node2D.new()
	field.add_child(node)
	contact.add(node)
	assert_bool(contact.is_alive()).is_true()

	contact.drop(node)
	node.queue_free()
	assert_bool(contact.is_alive()).is_false()


func test_only_what_is_within_reach_is_reported_nearest_first() -> void:
	var field := _field(_table(2))
	var origin := field.cell_centre(Vector2i(DEEP, 2))
	for sector in [1, 2, 3]:
		var cell := Vector2i(DEEP, sector)
		field._cells[cell] = field._generate(cell)

	var near := field.contacts_in_range(origin, 10000.0)
	assert_int(near.size()).is_greater(0)
	var previous := -1.0
	for contact in near:
		var d := contact.position().distance_to(origin)
		assert_float(d).is_less_equal(10000.0)
		assert_float(d).is_greater_equal(previous)
		previous = d

	# A long way off, the same space is silent
	assert_array(field.contacts_in_range(origin + Vector2(80000, 0), 10000.0)).is_empty()


func test_a_clone_wreck_is_labelled_like_any_other_wreck() -> void:
	# Nothing should be able to tell them apart before you get there.
	var clone: EncounterDef = load("res://entities/encounters/defs/clone_wreck.tres")
	var plain: EncounterDef = load("res://entities/encounters/defs/small_derelict.tres")
	assert_str(clone.contact_label).is_equal(plain.contact_label)
	assert_str(clone.contact_label).is_equal("DERELICT")


# --- Budgeted encounters -----------------------------------------------------

func _budgeted_table(budget: int) -> EncounterTable:
	var def := MarkerDef.new()
	def.id = &"rare"
	def.spread = 0.0
	def.nodes_per_encounter = 1
	def.budget = budget
	var table := EncounterTable.new()
	table.entries = [def]
	table.min_per_cell = 1
	table.max_per_cell = 1
	return table


func test_a_budgeted_encounter_runs_out() -> void:
	var field := _field(_budgeted_table(2))
	var found := 0
	for sector in range(0, 12):
		found += _nodes(field._generate(Vector2i(DEEP, sector))).size()
	assert_int(found).is_equal(2)
	assert_int(field.claimed_count(&"rare")).is_equal(2)


func test_a_claimed_place_keeps_its_encounter_when_you_go_back() -> void:
	var field := _field(_budgeted_table(1))
	var first := _nodes(field._generate(Vector2i(DEEP, 0)))
	assert_int(first.size()).is_equal(1)

	# Somewhere else is empty now — the budget is gone
	assert_array(_nodes(field._generate(Vector2i(DEEP, 1)))).is_empty()
	# But the place that claimed it still has it, however often you return
	assert_int(_nodes(field._generate(Vector2i(DEEP, 0))).size()).is_equal(1)
	assert_int(field.claimed_count(&"rare")).is_equal(1)


func test_an_unbudgeted_encounter_claims_nothing() -> void:
	var field := _field()
	field._generate(Vector2i(DEEP, 0))
	assert_array(Array(field.snapshot()["claimed"])).is_empty()


func test_claims_survive_a_save_and_a_new_game_clears_them() -> void:
	var field := _field(_budgeted_table(2))
	field._generate(Vector2i(DEEP, 0))
	field._generate(Vector2i(DEEP, 1))

	var restored := _field(_budgeted_table(2))
	restored.restore(field.snapshot())
	assert_int(restored.claimed_count(&"rare")).is_equal(2)
	# Still spent, so nowhere new hands one out
	assert_array(_nodes(restored._generate(Vector2i(DEEP, 5)))).is_empty()

	restored.reset()
	assert_int(restored.claimed_count(&"rare")).is_equal(0)


# --- Containers and wrecks ---------------------------------------------------

func test_a_container_comes_out_trophy_grade() -> void:
	var def: ContainerDef = load("res://entities/encounters/defs/lone_container.tres")
	var field := _field()
	var rng := RandomNumberGenerator.new()
	rng.seed = 7

	var entries := def.plan(rng, Vector2(140000.0, 0.0))
	assert_int(entries.size()).is_equal(1)

	var node := def.build(field, entries[0]) as ScrapNode
	assert_object(node).is_not_null()
	assert_bool(node.is_trophy).is_true()
	assert_int(node.hits_left).is_equal(ScrapNode.TROPHY_HITS)
	assert_str(node.kind).is_equal("Container")
	assert_float(absf(node._rotation_speed)).is_between(def.min_drift_spin, def.max_drift_spin)
	def.release(node)


func test_a_container_does_not_breathe() -> void:
	# It keeps the sparkles that mark it as worth taking, but a pulsing box reads as soft.
	var def: ContainerDef = load("res://entities/encounters/defs/lone_container.tres")
	var field := _field()
	var rng := RandomNumberGenerator.new()
	rng.seed = 7
	var box := def.build(field, def.plan(rng, Vector2(140000.0, 0.0))[0]) as ScrapNode

	assert_bool(box.is_trophy).is_true()
	assert_object(box.sparkle_particles).is_not_null()
	assert_object(box._trophy_pulse_tween).is_null()
	def.release(box)


func test_ordinary_trophy_scrap_still_breathes() -> void:
	# The pulse is how a rare lump of scrap catches the eye; only containers opt out.
	var scrap := auto_free(ResourceNodePool.get_instance("Scrap1", self)) as ScrapNode
	scrap.is_trophy = true
	assert_object(scrap._trophy_pulse_tween).is_not_null()
	ResourceNodePool.return_instance(scrap)


func test_a_wreck_carries_a_hold_worth_salvaging() -> void:
	var def: WreckDef = load("res://entities/encounters/defs/small_derelict.tres")
	var field := _field()
	var rng := RandomNumberGenerator.new()
	rng.seed = 11

	var entries := def.plan(rng, Vector2(140000.0, 0.0))
	assert_int(entries.size()).is_equal(1)
	assert_int(entries[0]["loot"].size()).is_between(def.min_loot, def.max_loot)

	var wreck := def.build(field, entries[0]) as DerelictShip
	assert_object(wreck).is_not_null()
	assert_int(wreck.loot.size()).is_equal(entries[0]["loot"].size())
	assert_bool(wreck.hull_only).is_false()
	assert_int(wreck.max_hits()).is_equal(DerelictShip.HITS)
	for id in wreck.loot:
		assert_bool(GemData.is_gem(id)).is_true()
	def.release(wreck)


func test_a_field_wreck_reports_the_ring_it_is_riding() -> void:
	# Anything matching its velocity to salvage it has to know it is moving, or it slides
	# out of harvest range partway through.
	var sun := auto_free(PLANET_SCENE.instantiate()) as Planet
	sun.planet_type = Planet.PlanetType.SUN
	sun.radius = 100.0
	add_child(sun)
	sun.global_position = Vector2.ZERO

	var table := EncounterTable.new()
	table.entries = [load("res://entities/encounters/defs/small_derelict.tres")]
	table.min_per_cell = 1
	table.max_per_cell = 1

	var field := _field(table)
	var wrecks := _nodes(field._generate(Vector2i(DEEP, 3)))
	assert_int(wrecks.size()).is_greater(0)

	for wreck in wrecks:
		var speed: float = (wreck as DerelictShip).get_orbital_velocity().length()
		assert_float(speed).is_equal_approx(field.band_rate(DEEP) * wreck.global_position.length(), 0.5)
		assert_float(speed).is_greater(1.0)

	# An abandoned ship has no ring under it, so it still reports only its own drift
	var adrift := DerelictShip.spawn(field, null, ["shard"], Vector2.ZERO, Vector2(7, 0), 0.0, 0.0, 5)
	assert_float(adrift.get_orbital_velocity().length()).is_equal_approx(7.0, 0.01)
	adrift.queue_free()
	for wreck in wrecks:
		wreck.queue_free()


func test_a_field_wreck_is_not_saved_twice() -> void:
	# The field rebuilds it from the seed, so the save must leave it alone or a copy is
	# left behind on every load.
	var def: WreckDef = load("res://entities/encounters/defs/small_derelict.tres")
	var field := _field()
	var rng := RandomNumberGenerator.new()
	rng.seed = 11
	var wreck := def.build(field, def.plan(rng, Vector2(140000.0, 0.0))[0]) as DerelictShip

	assert_bool(wreck.transient).is_true()
	assert_array(DerelictShip.snapshot_all(get_tree())).is_empty()

	# An ordinary abandoned ship in the same world still is saved
	var kept := DerelictShip.spawn(field, null, ["shard"], Vector2.ZERO, Vector2.ZERO, 0.0, 0.0, 5)
	assert_int(DerelictShip.snapshot_all(get_tree()).size()).is_equal(1)

	def.release(wreck)
	kept.queue_free()


func test_a_clone_wreck_needs_the_players_own_hull() -> void:
	# It is built from the ship's polygons, so with no ship there is nothing to copy and
	# it declines to place anything rather than spawning an invisible hull.
	var def: WreckDef = load("res://entities/encounters/defs/clone_wreck.tres")
	assert_object(def.hull).is_null()
	assert_int(def.budget).is_greater(0)

	var field := _field()
	var rng := RandomNumberGenerator.new()
	rng.seed = 2
	assert_object(def.build(field, def.plan(rng, Vector2(140000.0, 0.0))[0])).is_null()


func test_the_shipped_table_offers_all_four_encounters() -> void:
	var table: EncounterTable = load("res://entities/encounters/tables/deep_space.tres")
	var ids := {}
	for def in table.entries:
		ids[String(def.id)] = def
	assert_array(ids.keys()).contains(
		["debris_cluster", "lone_container", "small_derelict", "clone_wreck"])
	# Clusters are the common case; the rest are detours
	for rare in ["lone_container", "small_derelict", "clone_wreck"]:
		assert_float(ids[rare].weight).is_less(ids["debris_cluster"].weight)
	# Only the clone wreck is rationed
	assert_int(ids["clone_wreck"].budget).is_greater(0)
	for common in ["debris_cluster", "lone_container", "small_derelict"]:
		assert_int(ids[common].budget).is_equal(0)


func test_a_spawned_node_is_set_adrift_on_its_rings_rate() -> void:
	var sun := auto_free(PLANET_SCENE.instantiate()) as Planet
	sun.planet_type = Planet.PlanetType.SUN
	sun.radius = 100.0
	add_child(sun)
	sun.global_position = Vector2.ZERO

	# Clusters only, and certain to fire: this is about the orbit a spawned node is put
	# on, and a clone wreck would decline to build with no player ship to copy.
	# duplicate() keeps that out of the shared resource other tests load.
	var table := (load("res://entities/encounters/tables/deep_space.tres") as EncounterTable).duplicate()
	var clusters: Array[EncounterDef] = [load("res://entities/encounters/defs/debris_cluster.tres")]
	table.entries = clusters
	table.chance_per_cell = 1.0
	var field := _field(table)
	var nodes := _nodes(field._generate(Vector2i(DEEP, 7)))
	assert_int(nodes.size()).is_greater(0)

	for node in nodes:
		var motion = (node as OrbitalNode)._orbital_motion
		assert_bool(motion.initialized).is_true()
		assert_object(motion.orbital_body).is_equal(sun)
		var rate: float = motion.get_speed_radians_per_second()
		assert_float(rate).is_equal_approx(field.band_rate(DEEP), 1e-9)
		# Everything in the ring turns at one rate, so a cluster keeps its shape
		assert_float(motion.orbital_distance).is_equal_approx(node.global_position.length(), 0.5)
		ResourceNodePool.return_instance(node)
